### ISSUE TITLE
システム構成図 追加修正

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/social-resistance-docs#31]
Re:gret
- [x] MySQLの追加
- [x] SlackとIncoming Webhooks / Slash Commandsで通信している記述を追加

**Comment by NNN-kakimoto** [comment]
6ab6a106a485132a0ab0242cfbf57bdd472090da

**Comment by tyokinuhata** [comment]
- [ ] HTTPS -> HTTPにするやつ

**Comment by NNN-kakimoto** [comment]
HTTPSそのものを削除してwebsocketだけにした
5c220720ff9ab44922d15c6591cb4497d311cfde
